### ISSUE TITLE
SELinux issues on LineageOS 17.1

### ISSUE THREAD

**Issue by SebiderSushi** [SebiderSushi/sdcard-w_inject#3]
On my OnePlus X, running LineageOS 17.1, `vold` is not permitted to execute `/system/bin/sdcard`.
However, i was unable to find any mentions of the SELinux denials on logcat nor rooted dmesg.

Anyone running android 10 or later is welcome to submit output of `adb logcat -d -b all | grep denied` or the specific denials while running this module.
If you want to, please install the `*_permissive.zip` from the releases while doing so. This will turn the SELinux domains `sdcardd` and `vold` into permissive mode. This allows all actions to be executed while all illegal actions that are attempted down the way should be logged.

**Comment by AntiKippi** [comment]
On my Galaxy S7 herolte, running Android 10 /e/OS  (a fork of LineageOS 17.1) everything works fine with the normal zip.

**Comment by SebiderSushi** [comment]
Thanks for reporting!
I never bothered to re-check this issue since i am daily driving neither LineageOS 17.1 nor this module.
Chances are that newer Magisk versions are simply more capable when it comes to injecting custom SELinux rules - given the timeframe i likely reproduced this issue on my end when Magisk 23 was the current version. I remember there were a bunch of SELinux injection related changes to Magisk ever since.

I guess that concludes this. If anyone else is actually affected by this issue and is running recent Magisk versions feel free to comment again.
